C
      MODULE MO_ORG
C
      IMPLICIT NONE
C
      LOGICAL            LWRITEE, LWRITED, LWRITEF, LWRITET, LTAMIT ,
     &                   LAISTEP, LDISTEP, LQWR   , LMOMIT , LGMON  ,
     &                   LNEAR  , LVEG   , LINBOX , LSICED , LSCEN  ,
     &                   LNOHALO, LTSEC  , LVTMT  , LPTOP0
C
      REAL   ::          AKHH   , FAKRMY , PTOP
C
      INTEGER ::         NZT    , NA     , NJ     ,
     &                   NA2    , NJ2    , NZTRD  , NRD1   , NRD2   ,
     &                   IAA    , JAA    , IEA    , JEA    ,
     &                   IAH    , JAH    , IEH    , JEH    ,
     &                   IAU    , JAU    , IEU    , JEU    ,
     &                   IAV    , JAV    , IEV    , JEV    ,
     &                   IAHGG  , JAHGG  , IEHGG  , JEHGG  ,
     &                   IAHCOMP, JAHCOMP, IEHCOMP, JEHCOMP,
     &                   NANF   , NENDE  , NZVA   , NAKJATA, NE     ,
     &                   NEAA   , NDEA   , NZVM   , NZVN   ,
     &                   NDAA   , NDDA   , NZVD   ,
     &                   IADGB  , JADGB  , IEDGB  , JEDGB  ,
     &                   NFORA  , NDFOR  , NZVF   ,
     &                   NZVT   , NTAA   , NDTA   ,
     &                   NDR    , NZVR   , NHORPH ,
     &                   NTASKS , 
     &                   NHDMXN , NDMXN  ,
     &                   IFEL   , JFEL   , INUMZRM, INUMZRN
C
C**** ORG      -   CB:GROESSEN FUER DIE ORGANISATION DES MODELLS
C**
C**   BESCHREIBUNG DER VARIABLEN:
C**   NZT      :   AKTUELLER ZEITSCHRITT
C**   NA,NJ,NE :   INDIZES FUER ZYKLISCHE VERTAUSCHUNG DER DREI
C**                ZEITEBENEN
C**                NA ENTSPRICHT DEM ZEITPUNKT NZT - 1
C**                NJ ENTSPRICHT DEM ZEITPUNKT NZT
C**                NE ENTSPRICHT DEM ZEITPUNKT NZT + 1
C**   NA2,NJ2  :   INDIZES FUER ZYKLISCHE VERTAUSCHUNG VON ZWEI
C**                ZEITEBENEN
C**                NA2 ENTSPRICHT DEM ZEITPUNKT NZT - 1
C**                NJ2 ENTSPRICHT DEM ZEITPUNKT NZT
C**
C**   NZTRD    :   ZEITSCHRITTNUMMER DER LETZTEN RANDDATEI-AUFDATIERUNG
C**   NRD1,NRD2:   INDIZES FUER ZYKLISCHE VERTAUSCHUNG VON DER BEIDEN
C**                RANDDATEI-ZEITEBENEN
C**                NRD1 ENTSPRICHT DEM ZEITPUNKT NZTRD
C**                NRD2 ENTSPRICHT DEM ZEITPUNKT NZTRD + NDR
C**
C**   IAA,JAA  :   INDIZES DES LINKEN UNTEREN ECKPUNKTES DES
C**                MODELLGEBIETES
C**   IEA,JEA  :   INDIZES DES RECHTEN OBEREN ECKPUNKTES DES
C**                MODELLGEBIETES
C**   IAH,JAH  :   INDIZES DES LINKEN UNTEREN ECKPUNKTES DES GEBIETES
C**                MIT PROGNOSEN FUER H UND QDW
C**   IEH,JEH  :   INDIZES DES RECHTEN OBEREN ECKPUNKTES DES GEBIETES
C**                MIT PROGNOSEN FUER H UND QDW
C**   IAU,JAU  :   INDIZES DES LINKEN UNTEREN ECKPUNKTES DES GEBIETES
C**                MIT PROGNOSE FUER U
C**   IEU,JEU  :   INDIZES DES RECHTEN OBEREN ECKPUNKTES DES GEBIETES
C**                MIT PROGNOSE FUER U
C**   IAV,JAV  :   INDIZES DES LINKEN UNTEREN ECKPUNKTES DES GEBIETES
C**                MIT PROGNOSE FUER V
C**   IEV,JEV  :   INDIZES DES RECHTEN OBEREN ECKPUNKTES DES GEBIETES
C**                MIT PROGNOSE FUER V
C**   IAHGG,JAHGG    :
C**
C**   IEHGG,JEHGG    :
C**
C**   IAHCOMP,JAHCOMP:
C**
C**   IEHCOMP,JEHCOMP:
C**
C**
C**   NANF     :   ANFANGSZEITSCHRITT DER PROGNOSE
C**   NENDE    :   ENDZEITSCHRITT     DER PROGNOSE
C**   NZVA     :   ANZAHL DER VARIABLENNAMEN FUER DIE ANFANGSDATEI
C**                (SIEHE CORG)
C**   NAKJATA  :   JAHRESTAGSZAHL DES AKTUELLEN DATUMS (SIEHE: YAKDAT1)
C**   AKHH     :   STUNDE DES AKTUELLEN TAGES
C**
C**   NEAA     :   ZEITPUNKT DER ERSTEN ERGEBNISAUSGABE(GESAMT-GEBIET)
C**   NDEA     :   ZEITINKREMENT FUER ERGEBNISAUSGABEN ( "       "   )
C**   LWRITEE  :   WENN .TRUE., ERGEBNISAUSGABE DIESES ZEITSCHRITTS
C**   NZVM     :   ANZAHL DER VARIABLENNAMEN FUER DIE MONATSMITTELDATEI
C**                (SIEHE CORG)
C**   NZVN     :   ANZAHL DER VARIABLENNAMEN FUER DIE TAGESMITTELDATEI
C**                (SIEHE CORG)
C**
C**   NDAA     :   ZEITPUNKT DER ERSTEN ERGEBNISAUSGABE(DM-GEBIET)
C**   NDDA     :   ZEITINKREMENT FUER ERGEBNISAUSGABEN ( "   "   )
C**   LWRITED  :   WENN .TRUE., ERGEBNISAUSGABE DIESES ZEITSCHRITTS
C**   NZVD     :   ANZAHL DER VARIABLENNAMEN FUER DIE D - DATEI
C**                (SIEHE CORG)
C**   IADGB    :   INDIZES DES LINKEN UNTEREN ECKPUNKTES DES DM-GEBIETES
C**   JADGB    :
C**   IEDGB    :   INDIZES DES RECHTEN OBEREN ECKPUNKTES DES DM-GEBIETES
C**   JEDGB    :
C**
C**   NFORA    :   ZEITPUNKT DER ERSTEN FORTSETZUNGSAUSGABE (GESAMT-GEB)
C**   NDFOR    :   ZEITINKREMENT FUER   FORTSETZUNGSAUSGABEN(  "     " )
C**   LWRITEF  :   WENN .TRUE., ERGEBNISAUSGABE DIESES ZEITSCHRITTS
C**   NZVF     :   ANZAHL DER VARIABLENNAMEN FUER DIE F - DATEI
C**                (SIEHE CORG)
C**
C**   LWRITET  :   WENN .TRUE., AUSGABE DER TRAJEKTORIEN-DATEN
C**   NZVT     :   ANZAHL DER VARIABLENNAMEN FUER DIE TRAJEKTORIEN-
C**                DATEN (SIEHE CORG)
C**   NTAA     :   ZEITPUNKT DER ERSTEN AUSGABE DER TRAJEKTORIEN-DATEN
C**   NDTA     :   ZEITINKREMENT FUER AUSGABEN  DER TRAJEKTORIEN-DATEN
C**
C**   NDR      :   ZEITINKREMENT FUER RANDWERT-FELDER (RAHMEN-FELDER)
C**   NZVR     :   ANZAHL DER VARIABLENNAMEN FUER DIE RANDDATEI
C**                (SIEHE CORG)
C**   FAKRMY   :   VOM ZEITSCHRITTVERHAELTNIS ABHAENGIGER FAKTOR, MIT
C**                DEM RMY MULTIPLIZIERT WIRD (FAKRMY=DTNMI/DT FUER
C**                NMI-ZEITSCHRITT, SONST IST FAKRMY=1)
C**
C**   NHORPH   :   LAENGE EINES SLABS IN DER ECHAMPHYSIK
C**
C**   LAISTEP  :   WENN .TRUE., ADIABATISCHEN INMI-ZEITSCHRITT RECHNEN
C**   LDISTEP  :   WENN .TRUE., DIABATISCHEN  INMI-ZEITSCHRITT RECHNEN
C**
C**   LQWR     :   WENN .TRUE., QW IN DEN RANDFELDERN DEFINIERT
C**   LNEAR    :   WENN .TRUE., SUBROUTINE NEAEREC4 WIRD AUFGERUFEN
C**   LVEG     :   WENN .TRUE., MIT ZEITLICH VARIABLER VEGETATION
C**   LINBOX   :   WENN .TRUE., TRANSPORT BILANZEN WERDEN BERECHNET
C**   LMOMIT   :   WENN .TRUE., MONATSMITTEL BERECHNEN
C**   LGMON    :   WENN .TRUE., ES WIRD EIN GANZER MONAT IN EINEM JOB
C**                GERECHNET (BETR.: MONATS- BZW. TAGESMITTELBERECHNUG)
C**   LSCEN    :   WENN .TRUE., SCENARIO-RECHNUNG
C**   LSICED   :   WENN .TRUE., MEEREISDICKE AUS INPUT NEHMEN, SONST
C**                IN *ATMICE* SETZEN
C**   NHDMXN   :   ZEITINKREMENT [H] ZUM LOESCHEN VON AKKUMULIERTEN
C**                BZW. GEMITTELTEN GROSSEN
C**   NDMXN    :   ZEITINKREMENT [NZT] ZUM LOESCHEN VON AKKUMULIERTEN
C**                BZW. GEMITTELTEN GROSSEN
C**
C**   NTASKS   :   ANZAHL DER ZU VERWEND. PROZESSOREN IM MULTITASKING
C**
C**   VERFASSER:   D.MAJEWSKI
C     17.11.15: CONVERTED TO MODULE (LARS BUNTEMEYER)
C
      END MODULE MO_ORG
